---
title: "PCT Research: use by government"
format: html
toc: true
number-sections: true
execute:
    echo: false
---

# Purpose
Search for and review of evidence where PCT has been used by government to inform policy and decision making. This includes local, regional and national government.

# Department for Transport (DfT): LCWIP technical guidance

The DfT's [LCWIP technical guidance](https://www.gov.uk/government/publications/local-cycling-and-walking-infrastructure-plans-technical-guidance-and-tools
) ([PDF)](https://assets.publishing.service.gov.uk/media/5f32aa668fa8f57ac88dc9dc/cycling-walking-infrastructure-technical-guidance-document.pdf) states at s4.8:

> It is **strongly recommended** that authorities make use of the DfT-funded Propensity to Cycle Tool (PCT) through the LCWIP process.

The guidance goes onto explain what the tool is, how it can assist with LCWIP preparation for both planning and prioritisation, and determining future capacity needs.

The guidance also states at s5.15:

> Identifying desire lines and forecasting future commuter cycle flows can be **easily done** using the Propensity to Cycle Tool (PCT).


# Active Travel Fund (AFT) proforma guidance

Investment from active travel fund 4 (ATF4) to support delivery of objectives in the cycling and walking investment strategy (CWIS2). [Guidance note](https://www.gov.uk/government/publications/how-to-complete-the-active-travel-fund-4-proforma/guidance-note-for-local-authorities-to-support-completion-of-the-active-travel-fund-4-proforma) for local authorities to complete the ATF4 proforma states that eligible bids will be **assessed** against criteria including the propensity to convert short journeys to cycling based on the PCT. 


# Levelling up Fund -- FAQ (now withdrawn)

The [Levelling Up Fund FAQ](https://www.gov.uk/government/publications/levelling-up-fund-additional-documents/levelling-up-fund-frequently-asked-questions) suggests the use of the PCT for estimating cycling trips for corridors. Noted that this guidance was withdrawn in June 2022. 


# Welsh Government - Active Travel Guidance (ATAG)

The Welsh Government's [Active Travel Guidance (ATAG)](https://www.gov.wales/active-travel-act-guidance-atag) ([PDF](https://www.gov.wales/sites/default/files/consultations/2025-11/active-travel-guidance-2025-en_0.pdf)]

Welsh Government directs 

Table 10.1: Additional factors that could be considred during scheme of priorisation:

- Criterion: Propensity to Cycle
- Source of data: Propensity to Cycle Tool


# Active Travel: local authority toolkit (now withdrawn)

DfT [guidance](https://www.gov.uk/government/publications/active-travel-local-authority-toolkit/active-travel-local-authority-toolkit) that lists various tools to assist authorities with planning, implementing and assessing active travel infrastructure. Noted that this guidance was withdrawn in August 2022.

Guidance lists PCT as a tool to assist with strategic planning, prioritise investments and interventions to promote cycling.


# Active Travel England -- Active Travel Scheme Sketch Tool

Active Travel England (ATE) provide a [Scheme Browser tool](https://plan.activetravelengland.gov.uk) that allows user to sketch or upload an already planned scheme and then overlay outputs for various tools as its own layer. Among the tools available is the PCT which displays the propensity to cycle trips for each route segment for both commuting and school trips and under various scenarios (Baseline, Goverment Target, Go Dutch).