project:
  type: website
  render:
    - index.qmd
    - 2026-analysis.qmd
    - report-pct.qmd
    - ideas.qmd

website:
  title: "Transforming Strategic Active Travel Network Planning Internationally"
  repo-url: https://github.com/itsleeds/ics
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Impact Report"
        href: report-pct.qmd
      - text: "Ideas"
        href: ideas.qmd
    right:
      - icon: github
        href: https://github.com/itsleeds/ics
        aria-label: GitHub
