project:
  type: website
  render:
    - index.qmd
    - report.qmd
    - report-pct.qmd
    - plan.qmd
    - ideas.qmd
    - lcwips.qmd

website:
  title: "Transforming Strategic Active Travel Network Planning Internationally"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: report.qmd
      - text: "Plan"
        href: plan.qmd
      - text: "Ideas"
        href: ideas.qmd
      # - text: "LCWIP funding"
      #   href: lcwips.qmd
