---
title: "Project Plan"
subtitle: "Implementation plan and timeline"
date: last-modified
---

# Project Plan

## Week 1: Induction and Scoping (20 hours) 

Mandatory Training (4 hours): Attend the induction session on Monday 21st July (12:30-16:00). 

Desk Research (16 hours): 

Reading-up on the PCT and subsequent tools, including the [NPT manual](https://www.npt.scot/manual/).

Create a typology of key stakeholders

Basic exploration data from previous surveys with basic results.

Start on % LCWIPs using PCT and other tools

## Week 2: Outreach and Initial Data Collection (20 hours) 

Draft an online survey and semi-structured interview questions for NPT users and stakeholders. 

Share survey draft with stakeholders, pilot and refine based on feedback.
<!-- Stakeholder Outreach (10 hours): Begin contacting key stakeholders by email. Aim to get responses from practitioners and arrange a 2-day research trip to Scotland for the following week.  -->

Plan survey distribution and outreach strategy to ensure a diverse range of respondents, including local authorities, transport planners, and advocacy groups.

Analysis of data from previous surveys to inform the current survey design and outreach strategy.

## Week 3: Questionnaire send-out and data collection (20 hours)

Send out the draft survey to stakeholders for feedback.

Analyse data on LCWIP contents.

Explore international impacts

- Search results mentioning PCT in a policy context, e.g. site:govt.nz "propensity to cycle" and for other countries.

## Week 4: Data Analysis and Follow-up (20 hours) 

<!-- Send out the online survey to the stakeholder database to gather quantitative data on tool usage, level of satisfaction, impact on planning decisions, and feature requests. -->

Analysis of LCWIPs and funding data.

## Week 5: Additional Analysis and Dissemination (20 hours) 

Analysis (15 hours): Analyse the results from the LCWIP text analysis. Synthesise the findings to identify key themes, impact case studies, and authorities who have made the most extensive use of the tools.

<!-- Follow-up Interviews (5 hours): Conduct follow-up interviews via video call with any stakeholders who were unavailable during the Scotland trip. -->

- Test automated workflow to extract information from documents using API calls to LLMs? (Chris)

Final Report: Compile all evidence into a comprehensive impact report. This report will include an analysis of the PCT's reach, case studies of its application, and an assessment of its influence on transport policy and infrastructure decisions.

Optional: contributing to a paper about the tools.